### model
model_name_or_path: Qwen/Qwen2.5-14B
trust_remote_code: false

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: examples/deepspeed/ds_z3_config.json  # choices: [ds_z0_config.json, ds_z2_config.json, ds_z3_config.json]

### dataset
dataset: s1-qwen-base-template
template: qwen # must align with model_name_or_path
cutoff_len: 4096
max_samples: 100000
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4

### output
report_to: wandb
run_name: sft_qwen2.5-14b_s1-qwen-base-template_lr1e-5_mbs1-gac32-gpu4_imend
output_dir: ../save/checkpoint/sft_qwen2.5-14b_s1-qwen-base-template_lr1e-5_mbs1-gac32-gpu4_imend
logging_steps: 1
save_steps: 7 # for global-batch-size=128, step=66 is a complete epoch.
plot_loss: true
overwrite_output_dir: true
save_only_model: false

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 32
learning_rate: 1.0e-5
num_train_epochs: 10
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null


# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500
